### ISSUE TITLE
Maya 2015 VP2 support

### ISSUE THREAD

**Issue by thirstydevil** [zewt/zRigHandle#2]
Hi,

Really nice handle and great that is renders on top in VP2.  Have been using this on a new project but I have to swap to Maya2015.  Unfortunately it doesn't draw in VP2 in maya 2015.  If it's possible I'd like a fix, or a clue as to the problem and I'll attempt to fix myself.  Regards

Dave

**Comment by zewt** [comment]
Autodesk makes a lot of incompatible changes in each version of Maya, which makes backwards-compatibility hard for small projects like this.  I don't know what might have changed, and you might have issues with viewport selection as well (this has been improved a lot in newer releases).  You might want to download the SDK for Maya 2015 if it's still available and search around for the draw APIs for code to compare against.

**Comment by zewt** [comment]
If someone fixes this in a clean way I can apply a patch, but I'm not really planning on actively testing with a lot of old versions, so closing this for now.
